// Generated by CoffeeScript 1.8.0
(function() {
  var user;

  user = require('./user');

  exports.init = function(db) {
    return exports.User = db.model('User', user.schema);
  };

}).call(this);
