// Generated by CoffeeScript 1.8.0
(function() {
  var AuthController, BaseController, base, passport,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  passport = require('passport');

  base = require('./base');

  BaseController = base.BaseController;

  AuthController = (function(_super) {
    __extends(AuthController, _super);

    function AuthController() {
      return AuthController.__super__.constructor.apply(this, arguments);
    }

    AuthController.prototype.login = function(req, res, next) {
      req.session.redirectUrl = req.query['r'];
      return passport.authenticate('google')(req, res, next);
    };

    AuthController.prototype.login_callback = function(req, res, next) {
      passport.authenticate('google', {
        successRedirect: req.session.redirectUrl || '/',
        failureRedirect: '/'
      })(req, res, next);
      return req.session.redirectUrl = null;
    };

    AuthController.prototype.logout = function(req, res, next) {
      req.logout();
      return res.redirect('/');
    };

    return AuthController;

  })(BaseController);

  exports.controller = new AuthController();

}).call(this);
