// Generated by CoffeeScript 1.8.0
(function() {
  var BaseController;

  BaseController = (function() {
    function BaseController() {
      var func, name;
      for (name in this) {
        func = this[name];
        if ((name !== "constructor" && name !== "action") && name.indexOf("__") !== 0) {
          if (this.__before__) {
            this[name] = this.__wrap__(name, this.__before__, this[name]);
          }
          if (this.__after__) {
            this[name] = this.__wrap__(name, this[name], this.__after__);
          }
        }
      }
    }

    BaseController.prototype.__wrap__ = function(name, func_a, func_b) {
      return function(req, res, next) {
        func_a(req, res, next);
        return func_b(req, res, next);
      };
    };

    return BaseController;

  })();

  exports.BaseController = BaseController;

}).call(this);
