// Generated by CoffeeScript 1.8.0
(function() {
  var BaseController, HomeController, base, passport,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  passport = require('passport');

  base = require('./base');

  BaseController = base.BaseController;

  HomeController = (function(_super) {
    __extends(HomeController, _super);

    function HomeController() {
      return HomeController.__super__.constructor.apply(this, arguments);
    }

    HomeController.prototype.index = function(req, res, next) {
      return res.render('index.html', {});
    };

    return HomeController;

  })(BaseController);

  exports.controller = new HomeController();

}).call(this);
