// Generated by CoffeeScript 1.8.0
(function() {
  var auth, home;

  home = require('./home');

  auth = require('./auth');

  exports.home = home.controller;

  exports.auth = auth.controller;

}).call(this);
