// Generated by CoffeeScript 1.8.0
(function() {
  var models, mongoose;

  mongoose = require('mongoose');

  models = require('../models');

  exports.configure = function(app) {
    mongoose.connect('mongodb://localhost/stash');
    return models.init(mongoose);
  };

}).call(this);
