// Generated by CoffeeScript 1.8.0
(function() {
  var humanize, markdown;

  humanize = require('humanize');

  markdown = require("markdown").markdown;

  exports.JSON = {
    stringify: function(obj) {
      var result;
      result = JSON.stringify(obj);
      if ('string' === typeof result) {
        result = result.replace(/'/g, "&#39");
      }
      return result;
    }
  };

  exports.humanize = humanize;

  exports.markdown = markdown;

}).call(this);
