// Generated by CoffeeScript 1.8.0
(function() {
  var authController, controllers, homeController, querystring, requiresAuth;

  querystring = require('querystring');

  controllers = require('../controllers');

  authController = controllers.auth;

  homeController = controllers.home;

  requiresAuth = function(req, res, next) {
    if (!req.user) {
      return res.redirect('/auth/login/?' + querystring.stringify({
        r: req.originalUrl
      }));
    } else {
      return next();
    }
  };

  exports.configure = function(app) {
    app.get('/', homeController.index);
    app.get('/auth/login/', authController.login);
    app.get('/auth/callback/', authController.login_callback);
    return app.get('/auth/logout/', authController.logout);
  };

}).call(this);
