// Generated by CoffeeScript 1.8.0
(function() {
  var nunjucks, path;

  nunjucks = require('nunjucks');

  path = require('path');

  exports.configure = function(app) {
    var env;
    env = new nunjucks.Environment(new nunjucks.FileSystemLoader(['public/tpl', 'templates']));
    env.express(app);
    return exports.env = env;
  };

}).call(this);
